class Save



	def self.read(save_data, static_level=100)
		save_index_a_offset = 0xffc
		save_block_b_offset = 0x00E000
		trainer_id_offset = 0xa
		save_index_b_offset = save_block_b_offset + save_index_a_offset

		all_moves = File.read("./Reference_Files/save_constants/moves.txt").split("\n")
		all_mons = File.read("./Reference_Files/save_constants/mons.txt").split("\n")
		tables = {"erratic" => erratic_table, "medium_slow" => medium_slow_table}


		# if save_index odd should be at save_block B otherwise A


		# save_path = "./IE.sav"
		save = save_data


		save_index_a = save[save_index_a_offset..save_index_a_offset + 1].unpack("S")[0]
		save_index_b = save[save_index_b_offset..save_index_b_offset + 1].unpack("S")[0]
		block_offset = 0

		if save_index_b > save_index_a
			block_offset = save_block_b_offset
		end

		save = save[block_offset..block_offset + 57343]


		#comment this out later
		# block_offset = 0


		#change this to the larger of the two save indexes later
		save_index = [save_index_a, save_index_b].max
		# save_index = save_index_a

		rotation = (save_index % 14)
		total_offset = rotation * 4096


		new_trainer_id_offset = total_offset + trainer_id_offset
		trainer_id = save[new_trainer_id_offset..new_trainer_id_offset + 3].unpack("V")[0]
		box_offset = (20480 + 4 + total_offset) % 57344
		party_offset = (total_offset + 4096 + 0x238) % 57344




		box_data = ""
		box_data = save[box_offset..box_offset + 33599]

		party_data = save[party_offset..party_offset + 599]

		box_data += party_data





		(0..8).each do |n|
			box_start = ((n * 4096) + box_offset) % 57344
			pc_box = save[box_start..box_start + 4095]
			box_data += pc_box
		end



		trainer_string = save[new_trainer_id_offset..new_trainer_id_offset + 3]

		mon_count = 0

		box_suboffset = 0
		import_data = ""

		# p trainer_string.unpack("V")[0]

		n = 0
		while n < box_data.length
			break if n > 34200
			data = box_data[n..n+3]
			if data != trainer_string
				n += 4
				next
			else

				mon_data = box_data[n-4..n+75]

				begin
					pid = mon_data[0..3].unpack("V")[0]
					tid = mon_data[4..7].unpack("V")[0]
				rescue
					# binding.pry
				end
				sub_order = order_formats[pid % 24]

				key = tid ^ pid

				showdown_data = mon_data[32..-1]

				#decrypt with key

				decrypted = []
				(0..11).each do |m|
					start = m * 4
					block = showdown_data[start..start + 3].unpack("V")[0]
					decrypted << (block ^ key)
				end

				growth_index = sub_order.index(1)
				moves_index = sub_order.index(2)
				misc_index = sub_order.index(4)



				species_id = [decrypted[growth_index * 3]].pack('V').unpack('vv')[0]

				if species_id > 899
					species_id += 7
				end

				exp = decrypted[growth_index * 3 + 1]
				lvl = static_level
				nature = RomInfo.natures[pid % 25]

				
				move1 = all_moves[[decrypted[moves_index * 3]].pack('V').unpack('vv')[0]]
				move2 = all_moves[[decrypted[moves_index * 3]].pack('V').unpack('vv')[1]]
				move3 = all_moves[[decrypted[moves_index * 3 + 1]].pack('V').unpack('vv')[0]]
				move4 = all_moves[[decrypted[moves_index * 3 + 1]].pack('V').unpack('vv')[1]]

				ivs = [decrypted[misc_index * 3 + 1]][0]
				iv_stats = ["HP", "Atk", "Def", "Spe", "SpA", "SpD"]
				spread = {}

				iv_stats.each_with_index do |stat, i|
					spread[stat] = middle_bits_from_index(ivs, i * 5, 5)
				end
				ability_slot = middle_bits_from_index(ivs, 31, 1)

				moves = [move1, move2, move3, move4]
				
				set = {}

				import_data += all_mons[species_id].strip + "\n"
				import_data += "Level: #{lvl}\n"
				import_data += "#{nature} Nature\n"
				
				import_data += "IVs: "
				iv_stats.each do |stat|
					import_data += "#{spread[stat]} #{stat} / "
				end
				import_data = import_data[0..-4]
				import_data += "\n"
				
				import_data += "Ability: #{ability_slot}\n"
				moves.each do |m|
					import_data += "- #{m}\n"
				end
				import_data += "\n"
				mon_count += 1
				n += 44
			end


		end
		import_data
	end

	def self.order_formats
		[[1,2,3,4],			
		[1,2,4,3],			
		[1,3,2,4],			
		[1,3,4,2],			
		[1,4,2,3],			
		[1,4,3,2],			
		[2,1,3,4],
		[2,1,4,3],
		[2,3,1,4],
		[2,3,4,1],
		[2,4,1,3],
		[2,4,3,1],
		[3,1,2,4],
		[3,1,4,2],
		[3,2,1,4],
		[3,2,4,1],
		[3,4,1,2],
		[3,4,2,1],
		[4,1,2,3],
		[4,1,3,2],
		[4,2,1,3],
		[4,2,3,1],
		[4,3,1,2],
		[4,3,2,1]]
	end

	def self.middle_bits_from_index(number, m, n)
	  # Create a mask to extract 'n' bits
	  mask = (1 << n) - 1

	  # Shift the mask to align it with the desired starting bit and extract those bits
	  result = (number >> m) & mask

	  result
	end

	def self.get_level(species_id, exp, tables={})
		growth = growths[species_id]

		if growth == "MEDIUM_FAST"
			level = Math.cbrt(exp).floor
		elsif growth == "ERRATIC"
			level = search_table(tables["erratic"], exp)
		elsif growth == "MEDIUM_SLOW"
			level = search_table(tables["medium_slow"], exp)
		elsif growth == "FAST"
			level = Math.cbrt(exp * 5 / 4.0).floor
		elsif growth == "SLOW"
			level = Math.cbrt(exp * 4 / 5.0).floor
		end
	end


	def self.search_table(table, exp)
		level = 0
		table.each_with_index do |needed, i|
			if exp < needed
				next
			else
				level = i
				break
			end
		end
		return level
	end

	def self.erratic_table
		tbl = []
		(0..49).each do |n|
			tbl << ((n**3) * (100 - n)) / 50
		end

		(50..67).each do |n|
			tbl << ((n**3) * (150 - n)) / 100
		end

		(68..97).each do |n|
			tbl << (((1911 - 10 * n) / 3) * (n**3) / 500)
		end

		(98..100).each do |n|
			tbl << ((n**3) * (160 - n)) / 100
		end

		tbl
	end

	def self.medium_slow_table
		tbl = []
		(0..100).each {|n| tbl << ((6/5.0)*(n**3) - (15*n*n) + (100 * n) - 140).floor }
		tbl
	end




	def self.growths
		["MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","MEDIUM_FAST","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","FAST","FAST","MEDIUM_FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_SLOW","MEDIUM_FAST","FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_SLOW","SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","SLOW","SLOW","FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","FAST","FAST","FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","MEDIUM_SLOW","MEDIUM_FAST","FAST","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","FAST","FAST","FAST","FAST","MEDIUM_SLOW","FAST","FAST","SLOW","SLOW","FAST","FAST","FAST","FAST","MEDIUM_FAST","FAST","FAST","FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_SLOW","FAST","FAST","FAST","FAST","FAST","FAST","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","ERRATIC","ERRATIC","ERRATIC","FAST","FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","ERRATIC","ERRATIC","FAST","FAST","FAST","FAST","FAST","MEDIUM_SLOW","MEDIUM_SLOW","FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_FAST","FAST","MEDIUM_SLOW","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","FAST","ERRATIC","ERRATIC","MEDIUM_FAST","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","SLOW","MEDIUM_FAST","SLOW","MEDIUM_FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","FAST","FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","FAST","FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","MEDIUM_FAST","SLOW","MEDIUM_FAST","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","FAST","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","SLOW","SLOW","MEDIUM_SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","ERRATIC","ERRATIC","ERRATIC","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","SLOW","MEDIUM_SLOW","MEDIUM_FAST","FAST","SLOW","MEDIUM_FAST","SLOW","SLOW","FAST","MEDIUM_FAST","FAST","MEDIUM_SLOW","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","MEDIUM_FAST","SLOW","MEDIUM_SLOW","SLOW","SLOW","FAST","SLOW","MEDIUM_FAST","FAST","MEDIUM_SLOW","MEDIUM_FAST","SLOW","MEDIUM_SLOW","MEDIUM_FAST","SLOW","SLOW","SLOW","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","MEDIUM_FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","FAST","FAST","SLOW","SLOW","SLOW","FAST","FAST","FAST","FAST","FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","MEDIUM_SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_SLOW","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_SLOW","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","MEDIUM_FAST","SLOW","FAST","MEDIUM_FAST","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW","SLOW"]
	end










end